comment:
  layout: header, changes, diff
coverage:
  ignore:
    - test/.*
    - setup.py
  status:
    patch: false
codecov:
  token: 53a67d15-f4a0-4677-a938-672609bdb9f7
  disable_default_path_fixes: false
